services:
  biomate:
    build:
      context: .
      dockerfile: Dockerfile
    image: biomate:latest
    container_name: biomate
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./assets:/assets
      - ./data:/data
      - ./results:/results
      - ./inputs:/inputs
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"
    command: ["web-interface", "--port", "8080"]
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10m
      timeout: 10s
      retries: 3
      start_period: 10s
